apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asos-map
  namespace: windborne
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: windborne.malashikh.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asos-map
                port:
                  number: 80
  tls:
    - hosts:
        - windborne.malashikh.in
      secretName: windborne-tls
