apiVersion: v1
kind: Secret
metadata:
  name: mapbox
  namespace: windborne
type: Opaque
stringData:
  PUBLIC_MAPBOX_TOKEN: pk.eyJ1IjoidGhlbWRxIiwiYSI6ImNta2tkeXJzdDFkNjYzZ29tMmp4NTF1ejUifQ.fctCq2IYRLfdCr8W1b5Kew
